apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: basic-exporter-rolebinding
  namespace: "auto-jumpstarter"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: basic-exporter-role
subjects:
  - kind: ServiceAccount
    name: basic-exporter
    namespace:  "auto-exporters"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: basic-exporter-image-puller
  namespace: auto-builder 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: basic-exporter
    namespace: "auto-exporters"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: basic-exporter
  namespace: "auto-exporters"
