# Example of a minimal image with auto-app installed

name: auto-app

content:
  repos:
    - id: local
      baseurl: file:///workspace/src/bin
      priority: 10
  rpms:
    - auto-app

auth:
  # "password"
  root_password: $6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU.
