kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: aib-build
spec:
  description: |
     Exceute bash commands in a container with the tools needed for RHAS development.
  params:
    - name: cmd
      description: "Bash command to execute"
      type: string

  steps:
    - name: build
      image: ghcr.io/rhadp/builder:latest
      script: |
        #!/usr/bin/env bash
        set -x

        source /venv/bin/activate

        echo "PWD" && pwd
        echo "/workspace ->" && ls -la /workspace
        echo "/workspace/source ->" && ls -la /workspace/source
        echo "/opt/app-root/.config/jumpstarter ->" && ls -la /opt/app-root/.config/jumpstarter

  workspaces:
    - name: source
      description: The workspace where the source code is located
    - name: config-dir
      description: Workspace for mounting Jumpstarter client configuration
      mountPath: /opt/app-root/.config/jumpstarter