kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: aib-workspace-exec
spec:
  description: |
     Exceute caib commands.
  params:
    - name: client-name
      type: string
      description: "The jumpstarter client config"
      default: "default"
    - name: workspace
      description: "Name of the workspace"
      type: string
    - name: cmd
      description: "Command to execute"
      type: string

  steps:
    - name: exec
      image: ghcr.io/rhadp/builder:latest
      script: |
        #!/usr/bin/env bash
        set -x

        source /venv/bin/activate
        cd /workspace/source

        # Extract the values from the service account and params
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        CLIENT_NAME=$(echo "$(params.client-name)" | tr -d '[:space:]')

        # create the config loaction if it does not already exist
        CONFIG_DIR="/opt/app-root/.config/jumpstarter/clients"
        mkdir -p $CONFIG_DIR

        # write the jumpstarter config to the expected location
        echo "$(oc -n $NAMESPACE get secret $CLIENT_NAME -o jsonpath='{.data.config}' | base64 -d)" > "$CONFIG_DIR/$CLIENT_NAME.yaml"

        # Use the client name provided in the parameter
        jmp config client use $CLIENT_NAME

        # Set the Jumpstarter environment variables
        export JMP_CLIENT_CONFIG="$CONFIG_DIR/$CLIENT_NAME.yaml"

        # execute this command
        caib "workspace exec $(params.workspace) -- $(params.cmd)"

  workspaces:
    - name: source
      description: The workspace where the source code is located