kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: jmp-setup-sa-client
spec:
  description: |
    Create Jumpstarter client config from the user system account in Kubernetes,
    this requires that Jumpstarter is configured to trust authentication from K8s
  params:
    - name: namespace
      description: "The namespace where the Jumpstarter server is running"
      type: string
    - name: name
      description: "The Jumpstarter client name"
      type: string
    - name: insecure-tls
      description: "Use insecure tls for grpc"
      type: string
      default: "false"
    - name: tls-ca
      description: "CA Cert for the TLS endpoint"
      type: string
      default: ""

  results:
    - name: grpc-endpoint
      description: "The Jumpstarter grpc endpoint"
      type: string
    - name: config
      description: "The content of the generated Jumpstarter client config file"
      type: string

  steps:
    - name: setup-client
      image: ghcr.io/rhadp/runtime:latest
      env:
      - name: JMP_GRPC_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: jumpstarter-devspaces-config
            key: JUMPSTARTER_GRPC_ENDPOINT

      script: |
        #!/usr/bin/env bash
        set -x
        source /venv/bin/activate

        # setup the .kube correctly

        # Extract the values from the service account
        POD_TOKEN_FILE="/var/run/secrets/kubernetes.io/serviceaccount/token"
        POD_TOKEN=$(cat "$POD_TOKEN_FILE")
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        API_SERVER=$(oc whoami --show-server)

        # set ./kube/config correctly
        mkdir -p ~/.kube

        oc config set-cluster rhas \
          --server=$API_SERVER \
          --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

        oc config set-credentials basic-exporter \
          --token=$POD_TOKEN

        oc config set-context basic-exporter-ctx \
          --cluster=rhas \
          --user=basic-exporter \
          --namespace=$NAMESPACE

        oc config use-context basic-exporter-ctx

        # setup the jmp infrastructure

        CONFIG_DIR=$(workspaces.config-dir.path)
        CONFIG_FILE="$CONFIG_DIR/default.yaml"

        # generate jumpstarter client config
        cat <<-EOF > "$CONFIG_FILE"
        apiVersion: jumpstarter.dev/v1alpha1
        kind: ClientConfig
        metadata:
          namespace: $(params.namespace)
          name: $(params.name)
        endpoint: $JMP_GRPC_ENDPOINT
        tls:
          insecure: $(params.insecure-tls)
          ca: \"$(params.tls-ca)\"
        token: $POD_TOKEN

        drivers:
          allow: []
          unsafe: true
        EOF

        # create a jmp client
        # CLIENT_NAME normalization for used in jumpstarter/kubernetes
        CLIENT_NAME=$(echo "$(params.name)" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9-]/-/g; s/-\+/-/g; s/^-//; s/-$//' | cut -c1-63)
        if oc get client "$CLIENT_NAME" -n $(params.namespace) &>/dev/null; then
          oc delete client "$CLIENT_NAME" -n $(params.namespace) &>/dev/null || true
        fi

        jmp admin create client $CLIENT_NAME --insecure-tls --unsafe --nointeractive -n $(params.namespace) --oidc-username keycloak:$(params.name)

        # return the config
        cat ${CONFIG_FILE} > $(results.config.path)
        echo $JMP_GRPC_ENDPOINT > $(results.grpc-endpoint.path)
  
  workspaces:
    - name: config-dir
      description: The workspace which contains Jumpstarter client config file