apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jmp-get-lease
spec:
  description: |
    Acquire a lease from Jumpstarter using the provided client config.
  params:
    - name: client-name
      type: string
      description: The client intending to acquire the lease.
      default: "default"
    - description: A list of label exporters in the format key=value.
      name: exporter-labels
      type: array
    - default: '3600'
      description: Maximum wait time (in seconds) for lease acquisition before timeout.
      name: timeout
      type: string
    - default: '02:00:00'
      description: Maximum time (in HH:MM:SS format) for holding lease before relasing it.
      name: lease-duration
      type: string
    
  
  results:
    - description: The Lease ID from Jumpstarter
      name: jmp-lease-id
      type: string
  
  steps:
    - name: acquire-lease
      image: 'quay.io/jumpstarter-dev/jumpstarter:latest'      
      args: ["$(params.exporter-labels[*])"]

      script: |
        #!/usr/bin/env bash
        #set -eux
        set -x

        CONFIG_DIR="/root/.config/jumpstarter/clients"

        # Use the client name provided in the parameter
        echo "Using the client $(params.client-name)-pac"
        jmp config client use $(params.client-name)-pac

        # debugging
        jmp get exporters
  
  workspaces:
    - name: config-dir
      description: Workspace for mounting Jumpstarter client configuration
      mountPath: /root/.config/jumpstarter/clients