apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jmp-run-cmd
spec:
  description: |
    Run a command
  params:
    - name: client-name
      type: string
      description: "The jumpstarter client config"
      default: "default"
    - name: jmp-lease-id
      type: string
      description: "The lease ID to use for command execution"
    - name: jmp-cmd
      type: string
      description: "The commands to run"
  
  steps:
    - name: acquire-lease
      image: ghcr.io/rhadp/pipeline:latest 
      args: ["$(params.exporter-labels[*])"]

      script: |
        #!/usr/bin/env bash
        set -x
        source /venv/bin/activate

        # Extract the values from the service account and params
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        CLIENT_NAME=$(echo "$(params.client-name)" | tr -d '[:space:]')

        # create the config loaction if it does not already exist
        CONFIG_DIR="/opt/app-root/.config/jumpstarter/clients"
        mkdir -p $CONFIG_DIR

        # write the jumpstarter config to the expected location
        echo "$(oc -n $NAMESPACE get secret $CLIENT_NAME -o jsonpath='{.data.config}' | base64 -d)" > "$CONFIG_DIR/$CLIENT_NAME.yaml"

        # Use the client name provided in the parameter
        jmp config client use $CLIENT_NAME

        # Set the Jumpstarter lease environment variable
        export JMP_LEASE="$(params.jmp-lease-id)"
        
        # Run the command
        echo "Running cmd $(params.jmp-cmd)"
        
        jmp shell --lease "${JMP_LEASE}" <<-EOF
          $(params.jmp-cmd)
        EOF
  
  workspaces:
    - name: source
      description: The workspace where the source code is located