apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  namespace: auto-jumpstarter
  name: local-exporter
endpoint: grpc.auto-jumpstarter.apps.rhas.sandbox2478.opentlc.com:443
tls:
  ca: ""
  insecure: true
token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDg1Iiwic3ViIjoiZXhwb3J0ZXI6YXV0by1qdW1wc3RhcnRlcjpsb2NhbC1leHBvcnRlcjplZWViYjVjMi1lOWZjLTQxOWQtYWQ4Yy1jZmU5ODE5N2UyNzYiLCJhdWQiOlsianVtcHN0YXJ0ZXIiXSwiZXhwIjoxOTQyNDk2NjkwLCJpYXQiOjE3ODQ4MTY2OTB9.sWjawo_IvkH3FUjpJ0ChG7pBo55RBhxmuUzk3OeLTrew14tYnlTlpSc8ZicCCDB0R2E9DEitQARl-Xyv9T4T-w
grpcOptions: {}
export:
  power:
    type: jumpstarter_driver_power.driver.MockPower
