- name: run a local exporter
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE

  tasks:
    - name: local exporter
      include_role:
        name: roles/local-exporter

