apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pr-test
  annotations:
    # pipeline tasks
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/task-1: ".tekton/tasks/bash.yaml"
    pipelinesascode.tekton.dev/task-2: ".tekton/tasks/jmp-setup-sa-client.yaml"
    pipelinesascode.tekton.dev/task-3: ".tekton/tasks/jmp-get-lease.yaml"
    # pipeline events
    pipelinesascode.tekton.dev/on-event: "[push,pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, release]"
    #pipelinesascode.tekton.dev/on-path-changed: "[src/**]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
spec:
  params:
    # git repository (PAC template vars)
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: sender
      value: "{{ sender }}"

  podTemplate:
    nodeSelector:
      auto.node-role/builder: "true"
    #tolerations:
    #  - key: "architecture"
    #    operator: "equal"
    #    value: "arm"
    #    effect: "NoSchedule"

  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      # jumpstarter client config
      - name: namespace
        default: auto-jumpstarter
      - name: name
        default: rhas-starter
      - name: insecure-tls
        default: "true"
      - name: tls-ca
        default: ""
      - name: exporter-labels
        type: array
        default:
          - "device=test-device"
      - name: lease-timeout
        default: "3600"
      - name: lease-duration
        default: "00:20:00"
    
    workspaces:
      - name: shared-workspace
    
    tasks:


      - name: setup
        taskRef:
          name: jmp-setup-sa-client
        #runAfter:
        #  - clone-repo
        params:
          - name: namespace
            value: $(params.namespace)
          - name: name
            value: $(params.sender)
          - name: insecure-tls
            value: $(params.insecure-tls)
          - name: tls-ca
            value: $(params.tls-ca)
        workspaces:
          - name: config-dir
            workspace: shared-workspace

      - name: get-lease
        taskRef:
          name: jmp-get-lease
        runAfter:
          - setup
        params:
          - name: client-name
            value: $(params.name)
          - name: exporter-labels
            value: $(params.exporter-labels[*])
          - name: timeout
            value: $(params.lease-timeout)
          - name: lease-duration
            value: $(params.lease-duration)
          - name: client-config
            value: $(tasks.setup.results.config)
        workspaces:
          - name: jumpstarter-client-secret
            workspace: shared-workspace

      

    finally:
      - name: release
        taskRef:
          name: bash
        params:
          - name: cmd
            value: "pwd && ls -la"
        workspaces:
          - name: source
            workspace: shared-workspace

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
