apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pr-rpm-build
  annotations:
    # pipeline tasks
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/task-1: ".tekton/tasks/bash.yaml"
    pipelinesascode.tekton.dev/task-2: ".tekton/tasks/jmp-setup-client.yaml"
    pipelinesascode.tekton.dev/task-3: ".tekton/tasks/jmp-get-lease.yaml"
    pipelinesascode.tekton.dev/task-4: ".tekton/tasks/jmp-release-lease.yaml"
    pipelinesascode.tekton.dev/task-5: ".tekton/tasks/jmp-cleanup.yaml"
    pipelinesascode.tekton.dev/task-6: ".tekton/tasks/jmp-run-cmd.yaml"
    pipelinesascode.tekton.dev/task-7: ".tekton/tasks/aib-build-dev.yaml"
    pipelinesascode.tekton.dev/task-8: ".tekton/tasks/aib-cmd.yaml"
    pipelinesascode.tekton.dev/task-9: ".tekton/tasks/aib-workspace-create.yaml"
    pipelinesascode.tekton.dev/task-10: ".tekton/tasks/aib-workspace-exec.yaml"

    # pipeline events
    pipelinesascode.tekton.dev/on-event: "[push,pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    
    pipelinesascode.tekton.dev/on-path-changed: "[src/**,manifests/**]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
spec:
  params:
    # git repository (PAC template vars)
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: sender
      value: "{{ sender }}"

  podTemplate:
    nodeSelector:
      auto.node-role/builder: "true"
    #tolerations:
    #  - key: "architecture"
    #    operator: "equal"
    #    value: "arm"
    #    effect: "NoSchedule"

  pipelineSpec:
    params:
      # git repository (PAC template vars)
      - name: repo_url
      - name: revision
      - name: sender

      # jumpstarter client config
      - name: namespace
        default: auto-jumpstarter
      - name: name
        default: rhas-starter
      - name: manifest
        default: "manifests/auto-app.aib.yml"
      - name: exporter-labels
        type: array
        default:
          - "type=qemu"
      - name: lease-timeout
        default: "3600"
      - name: lease-duration
        default: "00:20:00"

    workspaces:
      - name: shared-workspace

    tasks:
      - name: setup
        taskRef:
          name: jmp-setup-client
        params:
          - name: client-name
            value: $(params.sender)-$(context.pipelineRun.name)
          - name: namespace
            value: $(params.namespace)
        workspaces:
          - name: source
            workspace: shared-workspace

      - name: clone-repo
        taskRef:
          name: git-clone
        runAfter:
          - setup
        params:
          - name: url
            value: "$(params.repo_url)"
          - name: revision
            value: "$(params.revision)"
        workspaces:
          - name: output
            workspace: shared-workspace

      - name: get-lease
        taskRef:
          name: jmp-get-lease
        runAfter:
          - clone-repo
        params:
          - name: client-name
            value: $(tasks.setup.results.jmp-client-name)
          - name: exporter-labels
            value: $(params.exporter-labels[*])
          - name: timeout
            value: $(params.lease-timeout)
          - name: lease-duration
            value: $(params.lease-duration)
        workspaces:
          - name: source
            workspace: shared-workspace

      - name: setup-workspace
        taskRef:
          name: aib-workspace-create
        runAfter:
          - clone-repo
        params:
          - name: client-name
            value: $(tasks.setup.results.jmp-client-name)
          - name: workspace
            value: $(tasks.setup.results.jmp-client-name)
        workspaces:
          - name: source
            workspace: shared-workspace

      - name: build-rpm
        taskRef:
          name: aib-workspace-exec
        runAfter:
          - setup-workspace
        params:
          - name: client-name
            value: $(tasks.setup.results.jmp-client-name)
          - name: workspace
            value: $(tasks.setup.results.jmp-client-name)
          - name: cmd
            value: "make build-rpm-local"
        workspaces:
          - name: source
            workspace: shared-workspace

      - name: build-os
        taskRef:
          name: aib-build-dev
        runAfter:
          - get-lease
          - build-rpm
        params:
          - name: client-name
            value: $(tasks.setup.results.jmp-client-name)
          - name: run-id
            value: $(context.pipelineRun.name)
          - name: manifest
            value: "$(params.manifest)"
          - name: workspace
            value: $(tasks.setup.results.jmp-client-name)
          - name: target
            value: "qemu"
          - name: architecture
            value: "arm64"
          - name: mode
            value: "image"
          - name: format
            value: "qcow2"
          #- name: extra-args
          #  value: "-o ./images/minimal.qcow2"
        workspaces:
          - name: source
            workspace: shared-workspace

      - name: flash
        taskRef:
          name: jmp-run-cmd
        runAfter:
          - build-os
        params:
          - name: client-name
            value: $(tasks.setup.results.jmp-client-name)
          - name: jmp-lease-id
            value: $(tasks.get-lease.results.jmp-lease-id)
          - name: jmp-cmd
            value: "j flasher flash oci://$(tasks.build-os.results.disk-image)"
          - name: image
            value: "ghcr.io/rhadp-examples/rhas-exporter:latest"
        workspaces:
          - name: source
            workspace: shared-workspace

      - name: validate
        taskRef:
          name: jmp-run-cmd
        runAfter:
          - flash
        params:
          - name: client-name
            value: $(tasks.setup.results.jmp-client-name)
          - name: jmp-lease-id
            value: $(tasks.get-lease.results.jmp-lease-id)
          - name: jmp-cmd
            value: "pytest tests/boot_test.py"
          - name: image
            value: "ghcr.io/rhadp-examples/rhas-exporter:latest"
        workspaces:
          - name: source
            workspace: shared-workspace

    finally:
      - name: cleanup
        taskRef:
          name: jmp-cleanup
        params:
          - name: client-name
            value: $(tasks.setup.results.jmp-client-name)
          - name: jmp-lease-id
            value: $(tasks.get-lease.results.jmp-lease-id)
          - name: workspace
            value: $(tasks.setup.results.jmp-client-name)
          - name: namespace
            value: $(params.namespace)
        workspaces:
          - name: source
            workspace: shared-workspace

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
