apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: maven-build
annotations:
  pipelinesascode.tekton.dev/task: "[git-clone]"
  pipelinesascode.tekton.dev/on-event: "[push,pull_request]"
  pipelinesascode.tekton.dev/on-target-branch: "[main, release]"
  #pipelinesascode.tekton.dev/on-path-changed: "[src/**]"
  pipelinesascode.tekton.dev/cancel-in-progress: "true"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
      
  podTemplate:
    nodeSelector:
      auto.node-role/builder: 'true'
    #tolerations:
    #  - key: "architecture"
    #    operator: "Equal"
    #    value: "arm"
    #    effect: "NoSchedule"

  pipelineSpec:
    workspaces:
    - name: shared-workspace
    tasks:
      - name: fetch-repo
        taskRef:
          - name: git-clone
        params:
        - name: url
          value: {{ repo_url }}
        - name: revision
          value: {{ revision }}
        workspaces:
        - name: output
          workspace: shared-workspace
      