FROM ghcr.io/rhadp/codespaces:latest

USER root

ARG TARGETARCH

# define some environment variables
ENV ARCH=${TARGETARCH:-arm64} \
    HOME=/home/tooling \
    APP_ROOT=/home/tooling \
    XDG_CONFIG_HOME=/home/tooling/.config 

# set the virtual environment for jumpstarter etc
ENV UV_PYTHON=python3.14 VIRTUAL_ENV=/venv

# TODO: add yoour own modifications here
ENV JUMPSTARTER_REPO=https://github.com/mickume/jumpstarter \
    JUMPSTARTER_VERSION=develop \
    RHAS_STARTER_REPO=https://github.com/rhadp-examples/rhas-starter \
    RHAS_STARTER_VERSION=main

# Install the rhas driver packages (local forks of jumpstarter drivers) directly from GitHub, and any other patches to Jumpstarter
RUN uv venv --clear /venv && \
    uv pip install "git+${JUMPSTARTER_REPO}@${JUMPSTARTER_VERSION}#subdirectory=python/packages/jumpstarter-all" \
        "git+${RHAS_STARTER_REPO}@${RHAS_STARTER_VERSION}#subdirectory=packages/rhas-driver-qemu" \
        "git+${RHAS_STARTER_REPO}@${RHAS_STARTER_VERSION}#subdirectory=packages/rhas-driver-opendal" \
        "git+${RHAS_STARTER_REPO}@${RHAS_STARTER_VERSION}#subdirectory=packages/rhas-driver-power"

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

USER 10001
ENV HOME=/home/user
WORKDIR /projects